spring.application.name=ojas-rag
logging.pattern.console=${LOGGING_PATTERN:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}

spring.ai.model.chat=ollama
spring.ai.ollama.chat.options.model=llama3.2:3b
# This is the default base url through which the spring application communicates to the AI models.
# There is no need to specify this as of now when the ollama is running locally, but need to specify
# the url when hosted in a cloud platform
spring.ai.ollama.base-url=http://localhost:11434

logging.level.org.springframework.ai.chat.client.advisor=debug
logging.level.com.ojashwa.springai=debug

spring.docker.compose.stop.command=down

spring.ai.vectorstore.qdrant.initialize-schema=true
spring.ai.vectorstore.qdrant.host=localhost
spring.ai.vectorstore.qdrant.port=6334
spring.ai.vectorstore.qdrant.collection-name=ojashwa-rag

# Embedding related configurations

# Tell Spring AI to use your specific embedding model
spring.ai.ollama.embedding.options.model=mxbai-embed-large

# Force Ollama to respect the strict 512 limit
spring.ai.ollama.embedding.options.num-ctx=512
